In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,6,32,7]], np.int64)  #converting list into 2d array

In [3]:
myarr[0, 1]   #first parameter is row_no and second parameter is column_no

6

In [4]:
myarr.shape


(1, 4)

In [5]:
myarr[0,1]=40

In [6]:
myarr


array([[ 3, 40, 32,  7]], dtype=int64)

In [7]:
m = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [8]:
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
zeros = np.zeros((2,5))   #makes 2d array of dimension of 2x5 of zeroes

In [10]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
rng = np.arange(7)    #returns an array of 0-number-1 

In [12]:
rng

array([0, 1, 2, 3, 4, 5, 6])

In [13]:
ispace = np.linspace(1,5,4)  #returns an array of four random numbers between 1 and 5 included

In [14]:
ispace


array([1.        , 2.33333333, 3.66666667, 5.        ])

In [15]:
i=np.linspace(1,5,5)

In [16]:
i

array([1., 2., 3., 4., 5.])

In [17]:
ui = np.identity(3)

In [18]:
ui

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
x = [[1,2,3],[4,5,6],[7,1,6]]

In [20]:
ar = np.array(x)  #converts 2d list into 2d array

In [21]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 6]])

In [22]:
ar.sum(axis=0)   #axis=0->means column, means giving sum columnwise 

array([12,  8, 15])

In [23]:
ar.sum(axis=1) #axis=1 means row

array([ 6, 15, 14])

In [24]:
ar.T       #transpose

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 6]])

In [25]:
 y = np.array([1,2,3,4,5])

In [26]:
y

array([1, 2, 3, 4, 5])

In [27]:
y.argmax()   #gives max element index

4

In [28]:
y.argsort()

array([0, 1, 2, 3, 4], dtype=int64)

In [29]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 6]])

In [32]:
y =ar[2,2]

In [33]:
y

6

In [34]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 2.44948974]])

In [35]:
np.where(ar>5)

(array([1, 2, 2], dtype=int64), array([2, 0, 2], dtype=int64))

In [36]:
ar


array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 6]])

In [38]:
np.count_nonzero(ar)

9